### ISSUE TITLE
to-do: Fix base_model.py

### ISSUE THREAD

**Issue by DreMukare** [DreMukare/AirBnB_clone#1]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    print(my_model)
  File "/home/runner/ahbnb-project/models/base_model.py", line 43, in __str__
    .format(self.__class__.__name__, self.id, self.__dict__)
AttributeError: 'BaseModel' object has no attribute 'id'

Resolve this issue

**Comment by DreMukare** [comment]
Fixed by changing functionality in models/engine/file_storage.py
